config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'search/index', as: :search
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    query = params[:q]
    page = 1

    Rails.cache.fetch([query, page]) do
      gateway = Flickr::Gateway.new({ text: params[:q] })
      response = gateway.search
      @photos = response.fetch(:photos)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def photo_url(photo)
    "https://live.staticflickr.com/#{photo['server']}/#{photo['id']}_#{photo['secret']}_w.jpg"
  end

  def flickr_photo_url(photo)
    "https://www.flickr.com/photos/#{photo['owner']}/#{photo['id']}"
  end
end

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Search on Flickr</h1>
  <p class="lead">Type some words to search some images on Flickr</p>
  <%= form_tag search_path, method: :get do %>
    <div class="form-group">
      <%= text_field_tag :q, nil, class: 'form-control', required: true %>
    </div>

    <p class="lead">
      <%= submit_tag 'Search', class: 'btn btn-primary btn-lg', role: '' %>
    </p>
  <% end  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Flickr API Demo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<div class="container-fluid">
  <div class="text-center">
    <% if @photos.present? %>
      <h3><%= "Search results for: #{params[:q]}" %></h3>
      <p class="lead">You can go to the source by clicking an image</p>
    <% else %>
      <h3><%= "Sorry no results found for #{params[:q]}" %></h3>
    <% end %>

    <%= link_to '< Back to Search', :back, class: 'btn btn-inverse' %>

    <% if @photos.present? %>
      <div class="row">
        <div class="col-sm">
          <% @photos.each do |photo| %>
            <%= link_to flickr_photo_url(photo), target: '_blank' do %>
              <%= image_tag photo_url(photo), class: 'img-thumbnail', alt: flickr_photo_url(photo) %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>